### ISSUE TITLE
Migrate repo to New Computers

### ISSUE THREAD

**Issue by hxrts** [new-computers/arena-toolkit#12]
Feel like this is already kind of a New Computers project anyway, may as well host the repo there.

**Comment by edouerd** [comment]
I'm never sure what the best method/practice is for migrating repos between orgs/people/etc., but I just invited you to NCWG org in github, and you can feel free to use any method fit if you'd like to move!

link: https://github.com/new-computers

**Comment by hxrts** [comment]
Thanks Ed! Just tried, it apparently I need privileges to create a repo on New Computers before making a transfer.

**Comment by hxrts** [comment]
got it!
